/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class GameMemoryStore {
  /** Create a new SQLite-backed memory store and initialize the database schema. */
  static create(dbUrl: string): Promise<GameMemoryStore>
  /** Add a new memory entry */
  addEntry(id: string, content: string, createdAt: number, metadataJson: string): Promise<void>
  /** Get a memory entry by ID. Returns JSON string of the entry. */
  getEntry(id: string): Promise<string>
  /** Delete a memory entry by ID */
  deleteEntry(id: string): Promise<void>
  /** List all memory entries. Returns JSON string array of entries. */
  listEntries(): Promise<string>
}
export declare class CoreGameEngine {
  /** Initialize the Rust GameEngine */
  static create(ollamaUrl: string | undefined | null, saveDir: string, dbUrl: string): Promise<CoreGameEngine>
  /** Starts the engine's main event loop in the background */
  start(): void
  /** Dispatch an event to the game engine */
  dispatchEvent(eventType: string, payloadJson: string): void
  /** Subscribe to all events */
  subscribe(callback: (event_json: string) => void): void
  /** Get the current state snapshot as a JSON string */
  getState(): Promise<string>
  /** Save the game */
  save(name: string, mode: string): Promise<string>
  /** Load the game */
  load(saveId: string): Promise<void>
  /** List all saves */
  listSaves(limit?: number | undefined | null): Promise<string>
  /** Delete a save */
  deleteSave(saveId: string): Promise<void>
  /** Get Memories */
  getMemories(optionsJson: string): Promise<string>
  /** Recall Memories */
  recallMemories(query: string, optionsJson: string): Promise<string>
  /** Clear Memories */
  clearMemories(): Promise<void>
  /** Get Memory Count */
  getMemoryCount(): Promise<number>
}
